config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :metrics, only: [:show]
  resources :jobs, only: [:show]

  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  comfy_route :cms_admin, :path => '/admin'

  comfy_route :blog_admin, :path => '/admin'
  comfy_route :blog, :path => '/blog'

  match '/challenge', to: redirect('http://challenge.la2050.org', 301), via: :get
  
  comfy_route :cms, :path => '/', :sitemap => false

end

app/models/metric.rb
class Metric < ActiveRecord::Base
  validates_presence_of :name
  validates :dream, inclusion: { in: [true, false] }

  has_many  :goal_taggings,
            as: :taggable

  has_many  :goals,
            through: :goal_taggings

  has_many  :data_points

  public

  # Right now metrics can only
  # have one goal.
  def goal_name
    if (goal = goals.first)
      goal.name
    else
      "No goal"
    end
  end

  def unit_symbol
    case data_unit
    when 'percentage'
      '%'
    when 'dollars'
      '$'
    else data_unit
    end
  end

  def action_items
    ActionItem.joins(:goals).includes(:goals).where("goals.id IN (#{goals.pluck(:id).join(',')})")
  end

  def percent_of_target
    point_1 = data_points.order('data_time ASC').first
    point_2 = data_points.order('data_time ASC').last
    return nil unless [point_1, point_2].all?

    ratio = point_1.value / point_2.value
    (ratio * 100).round
  end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  def show
    @metric = Metric.find_by_name(params[:id]) || Metric.find(params[:id])
    @action_items = @metric.action_items

    render :cms_layout => 'metric', :cms_blocks => {
      name: @metric.name,
      description: @metric.description,
      goal: @metric.goal_name,
      target_description: @metric.target_description
    }
  end
end

app/helpers/metrics_helper.rb
module MetricsHelper
  def metrics_from_params
    scope = Metric.joins(:goals).order('goals.name ASC, metrics.name ASC')
    if params[:goal].present?
      scope.includes(:goals).joins(:goals).where("goals.name = ?", params[:goal])
    else
      scope.all
    end
  end
end

app/views/metrics/_goal_metrics.haml
.goalmetrics
  - Goal.find_by_name(@cms_page.slug).metrics.each do |metric|
    .col-md-6
      .metric
        %i
        = link_to(metric.name, metric_path(metric))

app/views/metrics/_graph.haml
- unless @metric.percent_of_target.nil?
  .pillbox-wrap
    - if @metric.percent_of_target < 100
      .pillbox-outer
        .pillbox-inner{style: "width:#{@metric.percent_of_target.to_f}%;" }

      .pillbox-axis
        - @metric.data_points.each do |data_point|
          .pillbox-value{style: "width:#{data_point.percent_of_target.to_f}%;" }= data_point.value_with_units
          .pillbox-year{style: "width:#{data_point.percent_of_target.to_f}%;" }= data_point.data_time.year

    - else
      .pillbox-outer{style: "width:#{(100 / @metric.percent_of_target.to_f) * 100}%;" }
      .pillbox-inner.exceeds

      .pillbox-axis
        - @metric.data_points.each do |data_point|
          .pillbox-value{style: "width:#{data_point.percent_of_target.to_f / @metric.percent_of_target.to_f * 100}%;" }= data_point.value_with_units
          .pillbox-year{style: "width:#{data_point.percent_of_target.to_f / @metric.percent_of_target.to_f * 100}%;" }= data_point.data_time.year

app/views/metrics/_metrics.haml
- metrics_from_params.each do |metric|
  %tr
    %td
      = metric.name
      - metric.goals.each do |goal|
        = link_to goal.name, "/goals/#{goal.name}", class: "goallabel #{goal.color}"

    %td.text-right
      = link_to 'View Metric', metric_path(metric)

app/views/metrics/_target.haml
- if @metric.dream == true
  %dt This is one of our Dream Metrics, metrics we’d love to measure but don’t have data for.
  %dl
    Know how to measure this metric? Send us an email at connect@la2050.org
- elsif @metric.dream == false
  %dt Our target:
  %dl #{@metric.target_description}