config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :metrics, only: [:show]
  resources :jobs, only: [:show]

  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  comfy_route :cms_admin, :path => '/admin'

  comfy_route :blog_admin, :path => '/admin'
  comfy_route :blog, :path => '/blog'

  match '/challenge', to: redirect('http://challenge.la2050.org', 301), via: :get
  
  comfy_route :cms, :path => '/', :sitemap => false

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates_presence_of :title,
                        :employment_type

  has_many  :goal_taggings,
            as: :taggable

  has_many  :goals,
            through: :goal_taggings

  has_and_belongs_to_many :organizations
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include ActionView::Helpers::DateHelper
  def show
    @job = Job.find(params[:id])

    render :cms_layout => 'job', :cms_blocks => {
      job_title: @job.title,
      employment_type: @job.employment_type,
      posted: time_ago_in_words(@job.date_posted),
      location: @job.location,
      description: @job.description,
      to_apply: @job.to_apply,
      organizations: @job.organizations.map(&:name).join(', ')
    }
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def jobs_from_params
    Job.order("jobs.date_posted DESC")
  end
end

app/views/jobs/_jobs.haml
%tbody
	- jobs_from_params.each do |job|
		%tr
			%td
				= link_to job.title, job_path(job)
				- job.goals.each do |goal|
					= link_to goal.name, "/goals/#{goal.name}", class: "goallabel #{goal.color}"

			%td
				- job.organizations.each do |org|
					= "#{org.name}"
			%td= job.employment_type
			%td=  "#{time_ago_in_words(job.date_posted)} ago"